# harness-kit project config — the ONLY file to adapt per stack.
# Commands run via `bash -c`; empty commands are skipped with an info line.
# Note: npm needs the private registry token (GITHUB_TOKEN) from ~/.zshrc → wrap with `zsh -ic`.
# CI (autogenerated.pr-pipeline.yml) uses `npm clean-install` + package-lock.json; no packageManager field.
# Verified from package.json scripts.
# zsh -ic starts at kit cwd — commands must cd into the repo first.
HARNESS_LINT_CMD="zsh -ic 'cd /Users/yangjun/Desktop/project/ad-center-frontend && npm run lint'"           # eslint . && lint:css && prettier --check .
HARNESS_TYPECHECK_CMD="zsh -ic 'cd /Users/yangjun/Desktop/project/ad-center-frontend && npm run typecheck'" # nuxi typecheck
HARNESS_BUILD_CMD="zsh -ic 'cd /Users/yangjun/Desktop/project/ad-center-frontend && npm run build'"         # nuxi build (hard gate)
HARNESS_TEST_CMD="zsh -ic 'cd /Users/yangjun/Desktop/project/ad-center-frontend && npm run test:ci'"        # vitest run --silent

# Advisory
HARNESS_STYLE_CMD=""                              # prettier check already part of lint

# E2E / smoke set (assertion-lock scope, globs relative to repo root)
HARNESS_E2E_CMD=""
HARNESS_SMOKE_GLOB=""
